### ISSUE TITLE
 Create a subclass for implemetation of randomized (general) measurements ?

### ISSUE THREAD

**Issue by timmintam** [qiskit-community/povm-toolbox#6]
Do we need a class in between `POVMImplementation `and `RandomizedProjectiveMeasurements` ? Something like `RandomizedPOVMs` that would describe in a very general way randomized measurements (in general we could randomized POVMs; not only PVMs)

**Comment by mrossinek** [comment]
I think, for the time being this is not needed. If we were to consider an implementation of `RandomizedPOVMs` in the future, this would be the natural place to implement it, so I don't think we need to separately track this issue.
