### ISSUE TITLE
 feat: expose RNG in the `POVMSampler` class

### ISSUE THREAD

**Issue by timmintam** [qiskit-community/povm-toolbox#7]
The `POVMSampler` class should allow the user to specify the seed and/or full RNG used for the sampling.

**Comment by mrossinek** [comment]
Re-opening due to false closure. That commit originally referred to a different issue of another repo.

**Comment by timmintam** [comment]
Actually the user should set the seed directly on the ``BaseSamplerV2`` used internally by the ``POVMSampler``.
